### ISSUE TITLE
adaptive rtmp support

### ISSUE THREAD

**Issue by gjanblaszczyk** [videojs/video-js-swf#176]
Hi,

Are you planning to add support for adaptive rtmp?

Cheers,
gb

**Comment by mmcc** [comment]
To be honest, no, I seriously doubt we'll add support for additional RTMP features. Our RTMP support is already a little tenuous and we're trying to move what we can to HTML5 streaming.  If you're interested in ABR streaming, I'd say check out [videojs-contrib-hls](/videojs/videojs-contrib-hls) and [contrib-dash](/videojs/videojs-contrib-dash)

**Comment by misiek08** [comment]
Naprawdę warto przenieść się na HLS, bo RTMP jest niepraktyczne w każdym aspekcie i jego używanie przy aktualnym rozwoju HLS i wsparciu jest bez sensu. Zapraszam do kontaktu w razie gdybyś potrzebował pomocy.

EN:
You really should move to HLS, because RTMP is non-practical in any aspect and using it with current HLS compatibility and support makes no sense. Contact me if you need any help.
