### ISSUE TITLE
FC Subscribe Support

### ISSUE THREAD

**Issue by webcast33** [videojs/video-js-swf#202]
I am trying to use video.js with Flash fallback for live streams. The problem is that my live streams are originating from a CDN that requires the FC Subscribe call for RTMP. Recompiling the swf file myself is over my head. I tried modifying the flashvars, adding the rtmp.subscribe=true option, and replacing the object tag, but that just didn't work.

Is there any chance that the FC Subscribe call will be added to the video.hjs swf? Or can you suggest a work-around? I think video.js is great, but the inability to handle live RTMP would be a show-stopper.

Thanks very much.

**Comment by albertogasparin** [comment]
Great news @gkatsev. Do you have an ETA for a new release?

**Comment by gkatsev** [comment]
It's out as 5.2.0 and in videojs 5.17.0. That videojs release isn't out on the CDN yet but the swf is up on the CDN. You can grab it here: `http://vjs.zencdn.net/swf/5.2.0/video-js.swf`

Can be used like this:
```js
videojs.options.flash.swf = '//vjs.zencdn.net/swf/5.2.0/video-js.swf';
```

**Comment by albertogasparin** [comment]
Sorry to bother you again, but are you sure FC Subscribe changes have been included in v5.2.0? Because I have updated videojs to v5.17.0 and videojs-swf to v5.2.0 (I'm using `npm`) but the live videos do not load correctly. Instead, by manually compiling videojs-swf master they play successfully. 
Moreover, the changelog says that FC Subscribe fix is only in head, not in v5.2.0. Am I missing something?
Thanks

**Comment by gkatsev** [comment]
@albertogasparin nope, you're right. I was being an idiot. It hasn't been released yet.

**Comment by gkatsev** [comment]
Sorry about the confusion, I'll make a release today.
