### ISSUE TITLE
muted() is dependent on volume level 

### ISSUE THREAD

**Issue by forbesjo** [videojs/video-js-swf#226]
Looks like `muted()` is true when volume is set to 0, this is inconsistent with HTML5 video playback where muted is a tracked separately from volume.

**Comment by gkatsev** [comment]
I think this is because flash only has a concept of volume (http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/SoundTransform.html) and so, muted literally just means that the volume is set to 0. I'm not sure it's worth the complexity of tracking the last volume and muted separately. Especially since the behavior of the controls in Video.js 6 matches this behavior.

**Comment by marguinbc** [comment]
Created https://github.com/videojs/video-js-swf/pull/230 to potentially address this issue.

**Comment by gkatsev** [comment]
Yup, #230 will close this.
