### ISSUE TITLE
RTMP SecureToken authentication support

### ISSUE THREAD

**Issue by httpdigest** [videojs/video-js-swf#91]
Hi,

we would very much appreciate the support for RTMP SecureToken authentication, as we would like to prevent unauthenticated users/flashplayers to view a stream published via Wowza MediaServer.

Thanks!

**Comment by campones** [comment]
they said they won't fix it

**Comment by ouzhou** [comment]
sad!!!!!!!!!!!

**Comment by shscy** [comment]
WTF

**Comment by gkatsev** [comment]
Because of the looming end of life of flash and browsers disabling flash by default and everything else we have to work on, we can't justify spending much time on adding new features to flash. We have not really been asked about this much, and we don't have much expertise here.
If someone is interested and the code changes are minimal, we may be willing to accept a change but due to our work load, we won't be able to implement this feature ourselves.
